### PR TITLE
Updated the nl.po file & POT file

### PR DESCRIPTION
**Pull request by neoatomic**
* Completed to 100%
* Big cleanup
* Fresh POT file

### CODE REVIEW

**Comment by dhwz** [comment]
Why did you remove English help texts from the POT file?

**Comment by neoatomic** [comment]
@dhwz All is still there. but let me check.

Also had a crashlog/traceback when i tried to delete E2Bookmark from the settings menu.
https://pastebin.com/raw/2rckQSHE

And here is an error. Those fields are for the function. Not the function description.
https://github.com/betonme/e2openplugin-EnhancedMovieCenter/blob/master/src/EnhancedMovieCenter.py#L382-L384
Those need renaming.

**Comment by dhwz** [comment]
The context sensitive help texts are used a bit strange in EMC code.

You removed the msgstr text from the POT, but the msgstr is the text which needs to be translated. ;)

 #: EnhancedMovieCenter.py:378		  #: EnhancedMovieCenter.py:378
  msgid "HELP_Show directories"		  msgid "HELP_Show directories"
 -msgstr "Show or hide directories in the movielist"

**Comment by dhwz** [comment]
thx

**Comment by neoatomic** [comment]
@dhwz I restored the old POT. Not sure what happened there, especially as the nl.po and nl.mo where working fine. ;(

**Pull request merged**
