### PR TITLE
Update EitSupport for #132

### PR DESCRIPTION
**Pull request by betonme**
Bug fix for Issue #132 "Eit file show wrong languish"

### CODE REVIEW

**Comment by Seth72** [comment]
Hello have you solved it

**Comment by betonme** [comment]
Hopefully yes, please test it

**Comment by Seth72** [comment]
how

**Comment by Seth72** [comment]
in the expendebles 3 i sent to you in eit and meta is now german hmm not Swedish or have i done somting wrong

**Comment by betonme** [comment]
Ok, you have already replaced the file?

Then only the configure language should be shown.

You could configure it within the EMC setup or E2 setup.

**Comment by Seth72** [comment]
yes and in emc its  Swedish and if i start  enhanced and got to expendables and look at information about the Movie its is gemany now ok i will test to change in emc setup
i dont know if i took the correct file

**Comment by betonme** [comment]
Just the EitSupport.py

**Comment by Seth72** [comment]
dont get it to work. i have vuduo 2 blackhole 2.17 enhanced 3.74beta and newest  enhanced  dont work with blackhole 2.17, but on open blackhole 2.17 its does so i will try it tomorrow

regard seth

**Comment by Seth72** [comment]
hello . tried your solution on open blackhole and it doesnt show Swedish . the expenables 3 is now in germany, strange . the same result with blackhole on my vuduo2

regards Seth

**Comment by betonme** [comment]
Hi, this should only happen if Your E2 language is set to German. Can You
send me Your /etc/enigma2/settings or a screenshot of the language
settings. Thanks

2015-11-06 17:57 GMT+01:00 Seth72 <notifications@github.com>:

**Comment by Seth72** [comment]
whats the name of the file

**Comment by Seth72** [comment]
20151103 18:32 [EMC] LOAD PATH:
/hdd/movie
20151103 18:33 Setting EPG language: sv_SE
20151103 18:45 Setting EPG language: sv_SE
20151103 18:48 +++ EMC V3.7.4beta20131015 startup
20151103 18:48 Setting EPG language: sv_SE
20151103 18:48 Next trashcan cleanup in 372 minutes
20151103 18:48 [EMCMS] trashcan cleanup: nothing to delete...
20151103 18:51 +++ EMC V3.7.4beta20131015 startup
20151103 18:51 Setting EPG language: sv_SE
20151103 18:51 [EMC] LOAD PATH:
/hdd/movie
20151103 18:51 recordings exist... so next trashcan cleanup in -1071 minutes
20151103 18:51 [EMC] LOAD PATH:
/media/net/Tv/Barnfilmer Svenska
20151103 18:59 [emcRC] REC START for: 20151103 1859 - Kanal 5 HD (S) - The Big Bang Theory
20151103 19:21 recordings exist... so next trashcan cleanup in -1101 minutes
20151103 19:24 [EMCPlayer] Player closed by user
20151103 19:29 [emcRC] REC START for: 20151103 1929 - Kanal 5 HD (S) - The Big Bang Theory
20151103 19:32 [emcRC] REC END for: 20151103 1859 - Kanal 5 HD (S) - The Big Bang Theory
20151103 19:51 recordings exist... so next trashcan cleanup in -1131 minutes

**Comment by betonme** [comment]
Please test commit/be7362a

**Comment by Seth72** [comment]
how do i do that

2015-11-06 20:39 GMT+01:00 Frank Glaser <notifications@github.com>:

**Comment by betonme** [comment]
You have to download the file
https://github.com/betonme/e2openplugin-EnhancedMovieCenter/blob/be7362ac4cbde267f01a604c846cb1c1807d07a6/src/EitSupport.py

Then copy it to your receiver and replace the existing one.

**Comment by betonme** [comment]
You have to download the file
https://github.com/betonme/e2openplugin-EnhancedMovieCenter/blob/be7362ac4cbde267f01a604c846cb1c1807d07a6/src/EitSupport.py

Then copy it to your receiver and replace the existing one.

**Comment by Seth72** [comment]
hello i have now tried your solution on openpli, Vti but the same thats on blackhole
this file is Swedish ifo about the Movie and its contain only Swedish, so i Think it thats the problem but as a mention on older enhanded 1.1.0 on my old vuduo its can separat it there is 3 different languish. so either a have to edit all files or accept this beacuse this is the only and best Movie center around.
regards seth

**Comment by betonme** [comment]
Yes, the 1.1.0 has no IFO support.
We close this here and open a new request to make the ifo support optinal or with language support

**Comment by Seth72** [comment]
ok

2015-11-08 11:46 GMT+01:00 Frank Glaser <notifications@github.com>:

**Pull request merged**
